<?php
namespace ;
/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';


class AntSettings {
  static $_TSPEC;

  public $port = null;
  public $baudrate = 115200;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'port',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'baudrate',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['port'])) {
        $this->port = $vals['port'];
      }
      if (isset($vals['baudrate'])) {
        $this->baudrate = $vals['baudrate'];
      }
    }
  }

  public function getName() {
    return 'AntSettings';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->port);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->baudrate);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('AntSettings');
    if ($this->port !== null) {
      $xfer += $output->writeFieldBegin('port', TType::STRING, 1);
      $xfer += $output->writeString($this->port);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->baudrate !== null) {
      $xfer += $output->writeFieldBegin('baudrate', TType::I32, 2);
      $xfer += $output->writeI32($this->baudrate);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}


