/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ant_CONSTANTS_H
#define ant_CONSTANTS_H

#include "ant_types.h"

namespace robotics {

class antConstants {
 public:
  antConstants();

};

extern const antConstants g_ant_constants;

} // namespace

#endif
