/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ant_constants.h"

namespace robotics {

const antConstants g_ant_constants;

antConstants::antConstants() {
}

} // namespace

