<?php

// Setup the path to the thrift library folder
$GLOBALS['THRIFT_ROOT'] = 'thrift';	

// Load up all the thrift stuff
require_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';
require_once $GLOBALS['THRIFT_ROOT'].'/protocol/TBinaryProtocol.php';
require_once $GLOBALS['THRIFT_ROOT'].'/transport/TSocket.php';
require_once $GLOBALS['THRIFT_ROOT'].'/transport/TBufferedTransport.php';

// Load the package that we autogenerated for this tutorial
require_once $GLOBALS['THRIFT_ROOT'].'/packages/ant/Ant.php';
require_once $GLOBALS['THRIFT_ROOT'].'/packages/ant/Types.php';

// Create a thrift connection (Boiler plate)
$socket = new TSocket('localhost', '9070');
$transport = new TBufferedTransport($socket);
$protocol = new TBinaryProtocol($transport);

// Create an ant client
$client = new AntClient($protocol);

// Open up the connection
$transport->open();	
    
// Initialisation
$settings = new AntSettings();
$settings->port = "/dev/ttyACM0";
$settings->baudrate = 115200;
$client->init($settings);

// Actions
$client->walk(10);
echo "These boots are made for walking..";

// And finally, we close the thrift connection
$transport->close();

?>
